### ISSUE TITLE
Server Password Bug

### ISSUE THREAD

**Issue by SafariGaming** [TeaSpeak/TeaSpeak#324]
I add server password with edit virtual server button. But I could not remove it.

**Comment by WolverinDEV** [comment]
Fixed within the next build :)

**Comment by Chazotu** [comment]
Just tested its fixed in last build

**Comment by Home-Network** [comment]
We can't remove the password on our server. With the latest update. ( TeaSpeak-1.2.10-beta-4.tar.gz )
If you don't trust come on tv or so. 
Maybe it's working because you started from 0 but in our case it's no working at all no one can come. 
Stop close the issue. or come on my teaspeak to check yourself : home-network.ovh
