### ISSUE TITLE
Implement client_created and client_lastconnected client property

### ISSUE THREAD

**Issue by batizisanya** [TeaSpeak/TeaSpeak#350]
**Is your feature request related to a problem? Please describe.**
Please implement client_created and client_lastconnected timestamp as a client property. 

**Describe the solution you'd like**
client_created = timestamp for the first connection
client_lastconnected = timestamp for the last connection. Just update when connect. 

Reference: http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf 
p26, clientdblist

**Comment by WolverinDEV** [comment]
I'm not sure but withn the client view its already implemented.
May I for got that at the db list.

**Comment by WolverinDEV** [comment]
```
                    pArgs->result->operator[](pArgs->resultIndex)["client_created"] = created;
                    pArgs->result->operator[](pArgs->resultIndex)["client_lastconnected"] = lastConnected;
```
Its already implemented :)

**Comment by zafai** [comment]
I need to reopen this problem.
The bot jts3servermod is using %CLIENT_CREATED% to get the information when the user visited the first time atm the bot is unable to replace %CLIENT_CREATED% because the information is not included into the output.

Command:
`clientinfo clid=X`

The user ts3cloud added here a example of the output from teamspeak https://github.com/TeaSpeak/TeaSpeak/issues/17#issuecomment-368479562

Thank you in advance.

**Comment by WolverinDEV** [comment]
Fixed within the next version :)
