### ISSUE TITLE
Use github wiki

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#4]
Every github repo has its own wiki which can be used for docs like the serverquery notify stuff if you want to :)

**Comment by WolverinDEV** [comment]
Hey,
your idear was also my first intention, but i want to migrate a own dokumentation into my webside.
But the github wikki is also still an option.

~
Mal kurz was anderes:
Sachmal hättest du eig. lust vil. bei R4p3 dir wieder ein paar Post Likes zu holen und vil. deinen Beitrag für TeaSpeak zu schreiben? (Software gibt's sogar Gratis :P).
PS: Kannst dur ruig noch Zeit lassen, da ich nicht in den Release Mode gehen will bevor in einen Windows support habe... welcher sich als schwer erweist... bekommen random SIGABRT :D

**Comment by Bluscream** [comment]
Ja habe ich vor ist sogar schon geschrieben aber nicht veröffentlicht will teaspeak vorher selbst ein paar tage testen und das geht schwer solang ich bei meiner freundin und ohne zugriff aufn linux server bin. Also aktuell warte auch ich auf ne windows binary :'D

**Comment by Bluscream** [comment]
Wegen der sache mim wiki du schau dir mal gh-pages an da kannst du auch deine eigene domain nehmen ^^

**Comment by WolverinDEV** [comment]
Hallo ich habe schon von gh pages gehört finde diese aber unnötig sofern man einen eigenen Webserver besitzt xDHey es freut mich das du dich dafür interessierst xDUnd ja etwas Advertising schadet nie.Ich weiß leider noch nicht wirklich ob und wann ich die Windows Binary herausbringe da dies schwerer ist als es zuerst vermutet wurde. Des weiteren bin ich die Nächsten 2 Tage in Berlin und programmiere nicht.Hast du Telegramm? Dan müssten wir nicht immer über github.com schreiben

**Comment by Bluscream** [comment]
Bin auch grad in berlin für 2 wochen lass mal treffen x'D

**Comment by Bluscream** [comment]
Klar heisse genauso auf telegran

**Comment by WolverinDEV** [comment]
Heute abent alex wenn ich net tu fertig bin? Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [TeaSpeak/TeaSpeak] Use github wiki (#4)Von: Bluscream An: TeaSpeak/TeaSpeak Cc: WolverinDEV ,Comment Bin auch grad in berlin für 2 wochen lass mal treffen x'D

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TeaSpeak/TeaSpeak","title":"TeaSpeak/TeaSpeak","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TeaSpeak/TeaSpeak"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Bluscream in #4: Bin auch grad in berlin für 2 wochen lass mal treffen x'D"}],"action":{"name":"View Issue","url":"https://github.com/TeaSpeak/TeaSpeak/issues/4#issuecomment-355288143"}}}

**Comment by Bluscream** [comment]
@WolverinDEV du solltest deinen apikey da rauslöschen :) "alex"?

**Comment by WolverinDEV** [comment]
Schmal schreibst du net auf Telegramm?

**Comment by Bluscream** [comment]
Hab noch nix bekommen ^^

![](https://i.imgur.com/kIZZw3l.png)

**Comment by WolverinDEV** [comment]
Such mal WolverinDEV

**Comment by Chazotu** [comment]
Will be implemented in future on our own site.
