### ISSUE TITLE
mumble and teamspeak synchronisation

### ISSUE THREAD

**Issue by preterive** [TeaSpeak/TeaSpeak#42]
# Feature

mumble and teamspeak synchronisation

Detailed Description:
A function that synchronise The teamspeka3 server with a mumble server (channels and voice).

**Comment by WolverinDEV** [comment]
I realy like this idea.
I may add this later on :)

**Comment by MrFunken** [comment]
To think this idea a bit further,
it would generally nice to sync not only cross-platform, also two (and more) different TeaSpeak instances.
In this way, it would be possible to build HA-Clusters.

**Comment by WolverinDEV** [comment]
Hey,
@MrFunken I don't really get your idea. Why should it be necessary to sync one server over a couple or two servers?

**Comment by MrFunken** [comment]
Okay, how I explain it.. (maybe I have a different definition of synchronization, then you)
Here is an example.

I have 2 TeaSpeak Servers (preferred on two different locations). I start to load balance these 2 Servers by DNS or a Dedicated Loadbalancer. (Okay, a load-balanced Teamspeak is kinda useless) but have 2 Dedicated Servers running as one virtual will help in some cases.
For example, a DDoS Attack. One server goes down. Is this case, the clients will be redirected instantly to the 2nd server.
Result: A more stable experience for all TeaSpeak Users.


I know it is kinda of an enterprise or enthusiast feature.
But I have looking for a feature like this since I work with TeamSpeak.
I've managed some real big servers (1.3k Peak Clients each day).

Finally, I've written a script, that syncs Channels, Permissions etc. to a 2nd backup server.
But, this was only a.. emergency solution to have a lower downtime just in case.
We never could automate it as we want because, if some clients a moved to the 2nd Server and some are still on the 1st one. it feels more like 2 Separate servers, then one and they can't talk to each other.

I hope you can understand what I'm talking about.

**Comment by WolverinDEV** [comment]
Hey,
i think we have a really equal definition of synchronization (in this context).
I really understand your point but isn't it enough to use MySQL|MariaDB as SQL backed?
If you use a setup like this than you just have to start the second server which is the fallback when server A collapse, and all should run fine. Okey well as a little overkill you also could sync the TS file tree between this two servers but thats really not required and for my personal requirements a little to much.

I know that the solution i posted above is currently only working with TeamSpeak cause TeaSpeak currently not supports multiple backand's, but i already have that plan on my to do list, so TeaSpeak would support this solution too in the near future.

**Comment by preterive** [comment]
I think it is a good Funktion because mumble is a opensource teamspeak clone.

**Comment by schoerg** [comment]
@WolverinDEV I think the OP means something like this:

You have a channel on your server, clients can connect either via Mumble and Teamspeak and will see the same users and can communicate.

**Comment by WolverinDEV** [comment]
Well cause to the fact that TeaSpeak gets something more different as i thought, its impossible to implement mumble too.
