### ISSUE TITLE
Teaspeak on ARM

### ISSUE THREAD

**Issue by Shindanaide** [TeaSpeak/TeaSpeak#49]
## System Information
***Operating System***: Raspbian
***Operating System Type*** (x86|x64): Arm
***TeaSpeak Version***: Last

## Issue
***Reason for reporting this issue***:
No ARM compiled version. Not running on ARM Devices.

***Detailed Description***:
Would be awesome to host a ts3 server on a raspberry. Official ts3 has never supported it. Could you compile your software for ARM? It would be revolutionary for ts community!

**Comment by WolverinDEV** [comment]
I don't really know how I could cross compile Teaspeak for arm, but if this not the wold than I may would add some cind of support

**Comment by JonathanNet** [comment]
Yeah ARM support would be nice, so it can be on a raspberry pi :)

**Comment by Bluscream** [comment]
Indeed i can recall many people asking for this. It would also allow running a server on a phone for whatever reason

**Comment by WolverinDEV** [comment]
This isnt a "allow" think, its a complexity think.
Its really hard to have all these libraries build for a lot of different archs.

**Comment by schoerg** [comment]
And do you have experience with ARM?

**Comment by WolverinDEV** [comment]
Yes, but I never cross compiled something :D
But how hard could it be?

**Comment by Bluscream** [comment]
Dont you have to use an ARM device to compile for arm?

**Comment by Bluscream** [comment]
So, now that @WolverinDEV had a little chat about this and now that i own two ARM devices;
(i know that my phone is also running ARM but i'm not gonna assume we need a TeamSpeak server for android)
- [Raspberry Pi 3 Model B+](https://www.raspberrypi.org/products/raspberry-pi-3-model-b-plus/)
- [Raspberry Pi 3 Model B](https://www.raspberrypi.org/products/raspberry-pi-3-model-b/)

i'm gonna share some thoughts on this.

As far as i read into this there would be two ways for TeaSpeak to run on a RPi.

## Compile it natively for ARMhf
RPi devices up to the newest 3B+ use ARMv7_1 processors.

\+ Best method from a performance perspective
\- Would maybe require to compile/test on a ARM device?

## Compile it for i368 aka x86
Compiling TeaSpeak for x86 systems would not only allow it to run on x86 systems but also on RPi's because there's an x86 emulator for ARM devices that's called [exagear](https://eltechs.com/product/exagear-desktop) which also already allows to [install Teamspeak 3 Server on RPi devices](https://eltechs.com/run-teamspeak-3-server-on-raspberry-pi/).

\+ Allows to have TeaSpeak on 32bit devices
\+ Does definitly not require you to have an ARM device for testing and compilation
\- Requires an emulator that heavily impacts performance (https://www.raspberrypi.org/forums/viewtopic.php?p=305595#p305595)
\- Requires paid software (https://eltechs.com/product/exagear-desktop/exagear-desktop-features-and-prices-daily1/)

**Comment by Bluscream** [comment]
@WolverinDEV You can grab a Pi at any local electronics store for around 30 bucks or order it online. Also you can get root ssh access to my 3B+ if you want :)

**Comment by schoerg** [comment]
>Don't you have to use an ARM device to compile for arm?

no

**Comment by WolverinDEV** [comment]
merged to https://github.com/TeaSpeak/TeaSpeak/issues/252
