### ISSUE TITLE
After expiry, the license does not use the default license

### ISSUE THREAD

**Issue by BIOS-THE-ORIGINAL** [TeaSpeak/TeaSpeak#668]
My premium license expired yesterday and so the server was stopped, so today I am trying to restart the server and find that the server is stopped without using the default license.

 Operating system: Debian 9.12
 TeaSpeak version: [1.4.14-beta-5]
 I am using `experimental_31`: no

**Comment by cyberlimbo** [comment]
Same here...
I bought a new premium license, inserted the new code in config.yml before the
old license expires..
When i come back, the server needed to be restarted so the new key start being used.

**Comment by WolverinDEV** [comment]
Will be fixed in beta 6.
In general the server had only one shot to get the new license. If this fails you've to manually upgrade.
But for now the server will just restart and will fall back to the default license.

In future versions the server will may be able to down/upgrade on the fly, but this is more complicated than it sounds :D
