### ISSUE TITLE
Allow switching between IPv4/IPv6

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#86]
It would be neat if the config would contain a setting to configure wether clients can connect via

- IPv4 only
- IPv6 only
- IPv4 and IPv6 (default)

**Comment by WolverinDEV** [comment]
IPv6 is currently not supported :)
But it will be supported soon, but it isn't my major priority

**Comment by skokkk** [comment]
IMO I believe that IPV6 is a high priority and that you will be _shooting yourself in the foot_ if you do not implement it in your early design. 

IPV6 is the future whether we like it or not, it will also help a LOT with being able to directly interface with clients, since their IP address is their real IP (unless they're behind an IPV6 NAT, which is highly unlikely as cisco have barely perfected this even). 

You don't need to worry about the person's router's firewall or so. You can *cough* *cough* (ab)use the client's actual computer since the default firewall on most computers suck.

Either way, ARM64 devices are usually only given IPV6 addresses. You can also consider since there is no NAT, that you can directly have an open port on the user's device (depending on their firewall/antivirus ofc..), which can be used for p2p and in general you can use the user's device (with a lot of effort).

**Comment by schoerg** [comment]
I don't see how the CPU architecture to what IP you'll get.

**Comment by WolverinDEV** [comment]
Implemented (edit `virtualserver_host`. Example: (`serveredit virtualserver_host=0.0.0.0,[::]`)

**Comment by skokkk** [comment]
That wasn't an update that was me informing you guys it can possibly work
on windows that has native x64 Linux.

My IPV6 though works.

**Comment by GoRiLliAz** [comment]
hi ipv6 not workink for me in version 1.2.7 beta.
Thanks in advance for fix.
